name: Release

on:
  push:
    branches:
      - main
    tags:
      - '!*'

jobs:
  chrome:
    name: Publish release tag and changelog
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.OSLASH_BOT_TOKEN }}
      HUSKY: '0'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run all tests and collect test coverage
        run: npm run coverage
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage
          flags: unittests
          fail_ci_if_error: true
          verbose: true
      # Build everything so that gets added to the project as well.
      # For Actions, we'll need the fully compiled output (in `dist/`)
      - name: Build everything
        run: npm run build
      - name: Import OSlash bot's GPG key for signing commits
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.OSLASH_BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.OSLASH_BOT_GPG_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Generate release notes
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.OSLASH_BOT_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import-gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import-gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import-gpg.outputs.email }}
